/**
 * Data models for the dependency resolver.
 * Merkle DAG Node: resolver_types
 */

/**
 * Represents the environment context for a resolution.
 * This is used to select the correct pre-built native modules.
 */
export interface ResolutionEnvironment {
  /** Node.js version */
  node: string;
  /** Operating system (e.g., "linux", "darwin", "win32") */
  os: string;
  /** CPU architecture (e.g., "x64", "arm64") */
  cpu: string;
  /** C library ABI (e.g., "glibc-2.35", "musl") */
  abi?: string;
}

/**
 * Represents a single resolved dependency in the lock file.
 */
export interface ResolvedDependency {
  /** Subresource Integrity hash of the package tarball */
  integrity: string;
  /** Content-Addressable Storage hash of the package tarball */
  cas: string;
  /** Direct URL to the package tarball on the GitHub store */
  url: string;
}

/**
 * Represents the lock file generated by the resolver.
 * This provides a deterministic and reproducible dependency graph.
 */
export interface LockFile {
  /** Version of the resolver that generated this lock file */
  resolver: string;
  /** Environment for which this lock file was resolved */
  environment: ResolutionEnvironment;
  /**
   * A map of resolved dependencies.
   * Key is in the format "packageName@version".
   */
  dependencies: Record<string, ResolvedDependency>;
}

/**
 * Represents a single entry in the `packages.jsonl` index.
 */
export interface IndexEntry {
  /** Package name */
  name: string;
  /** Package version */
  version: string;
  /** Subresource Integrity hash of the package tarball */
  integrity: string;
  /** Content-Addressable Storage hash of the package tarball */
  cas: string;
  /** Direct URL to the package tarball on the GitHub store */
  url: string;
  /**
   * Hashes of individual files within the package.
   * Useful for fine-grained caching or analysis.
   */
  files?: Record<string, string>;
}
